// WhatsApp tarzı ülke kodu seçimi. dial = "+" olmadan rakam (örn. "90").
export interface Country { code: string; name: string; flag: string; dial: string }

export const COUNTRIES: Country[] = [
  { code: 'TR', name: 'Türkiye', flag: '🇹🇷', dial: '90' },
  { code: 'US', name: 'ABD', flag: '🇺🇸', dial: '1' },
  { code: 'GB', name: 'Birleşik Krallık', flag: '🇬🇧', dial: '44' },
  { code: 'DE', name: 'Almanya', flag: '🇩🇪', dial: '49' },
  { code: 'FR', name: 'Fransa', flag: '🇫🇷', dial: '33' },
  { code: 'NL', name: 'Hollanda', flag: '🇳🇱', dial: '31' },
  { code: 'AT', name: 'Avusturya', flag: '🇦🇹', dial: '43' },
  { code: 'BE', name: 'Belçika', flag: '🇧🇪', dial: '32' },
  { code: 'CH', name: 'İsviçre', flag: '🇨🇭', dial: '41' },
  { code: 'IT', name: 'İtalya', flag: '🇮🇹', dial: '39' },
  { code: 'ES', name: 'İspanya', flag: '🇪🇸', dial: '34' },
  { code: 'PT', name: 'Portekiz', flag: '🇵🇹', dial: '351' },
  { code: 'SE', name: 'İsveç', flag: '🇸🇪', dial: '46' },
  { code: 'NO', name: 'Norveç', flag: '🇳🇴', dial: '47' },
  { code: 'DK', name: 'Danimarka', flag: '🇩🇰', dial: '45' },
  { code: 'FI', name: 'Finlandiya', flag: '🇫🇮', dial: '358' },
  { code: 'PL', name: 'Polonya', flag: '🇵🇱', dial: '48' },
  { code: 'CZ', name: 'Çekya', flag: '🇨🇿', dial: '420' },
  { code: 'RU', name: 'Rusya', flag: '🇷🇺', dial: '7' },
  { code: 'UA', name: 'Ukrayna', flag: '🇺🇦', dial: '380' },
  { code: 'AZ', name: 'Azerbaycan', flag: '🇦🇿', dial: '994' },
  { code: 'KZ', name: 'Kazakistan', flag: '🇰🇿', dial: '7' },
  { code: 'GE', name: 'Gürcistan', flag: '🇬🇪', dial: '995' },
  { code: 'GR', name: 'Yunanistan', flag: '🇬🇷', dial: '30' },
  { code: 'RO', name: 'Romanya', flag: '🇷🇴', dial: '40' },
  { code: 'BG', name: 'Bulgaristan', flag: '🇧🇬', dial: '359' },
  { code: 'RS', name: 'Sırbistan', flag: '🇷🇸', dial: '381' },
  { code: 'HR', name: 'Hırvatistan', flag: '🇭🇷', dial: '385' },
  { code: 'HU', name: 'Macaristan', flag: '🇭🇺', dial: '36' },
  { code: 'IE', name: 'İrlanda', flag: '🇮🇪', dial: '353' },
  { code: 'CY', name: 'Kıbrıs', flag: '🇨🇾', dial: '357' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', dial: '373' },
  { code: 'AL', name: 'Arnavutluk', flag: '🇦🇱', dial: '355' },
  { code: 'MK', name: 'Kuzey Makedonya', flag: '🇲🇰', dial: '389' },
  { code: 'BA', name: 'Bosna Hersek', flag: '🇧🇦', dial: '387' },
  { code: 'SA', name: 'Suudi Arabistan', flag: '🇸🇦', dial: '966' },
  { code: 'AE', name: 'BAE', flag: '🇦🇪', dial: '971' },
  { code: 'QA', name: 'Katar', flag: '🇶🇦', dial: '974' },
  { code: 'KW', name: 'Kuveyt', flag: '🇰🇼', dial: '965' },
  { code: 'BH', name: 'Bahreyn', flag: '🇧🇭', dial: '973' },
  { code: 'OM', name: 'Umman', flag: '🇴🇲', dial: '968' },
  { code: 'IL', name: 'İsrail', flag: '🇮🇱', dial: '972' },
  { code: 'IR', name: 'İran', flag: '🇮🇷', dial: '98' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶', dial: '964' },
  { code: 'EG', name: 'Mısır', flag: '🇪🇬', dial: '20' },
  { code: 'MA', name: 'Fas', flag: '🇲🇦', dial: '212' },
  { code: 'DZ', name: 'Cezayir', flag: '🇩🇿', dial: '213' },
  { code: 'TN', name: 'Tunus', flag: '🇹🇳', dial: '216' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', dial: '218' },
  { code: 'ZA', name: 'Güney Afrika', flag: '🇿🇦', dial: '27' },
  { code: 'NG', name: 'Nijerya', flag: '🇳🇬', dial: '234' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', dial: '254' },
  { code: 'IN', name: 'Hindistan', flag: '🇮🇳', dial: '91' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', dial: '92' },
  { code: 'BD', name: 'Bangladeş', flag: '🇧🇩', dial: '880' },
  { code: 'CN', name: 'Çin', flag: '🇨🇳', dial: '86' },
  { code: 'JP', name: 'Japonya', flag: '🇯🇵', dial: '81' },
  { code: 'KR', name: 'Güney Kore', flag: '🇰🇷', dial: '82' },
  { code: 'ID', name: 'Endonezya', flag: '🇮🇩', dial: '62' },
  { code: 'MY', name: 'Malezya', flag: '🇲🇾', dial: '60' },
  { code: 'SG', name: 'Singapur', flag: '🇸🇬', dial: '65' },
  { code: 'TH', name: 'Tayland', flag: '🇹🇭', dial: '66' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', dial: '84' },
  { code: 'PH', name: 'Filipinler', flag: '🇵🇭', dial: '63' },
  { code: 'AU', name: 'Avustralya', flag: '🇦🇺', dial: '61' },
  { code: 'NZ', name: 'Yeni Zelanda', flag: '🇳🇿', dial: '64' },
  { code: 'CA', name: 'Kanada', flag: '🇨🇦', dial: '1' },
  { code: 'MX', name: 'Meksika', flag: '🇲🇽', dial: '52' },
  { code: 'BR', name: 'Brezilya', flag: '🇧🇷', dial: '55' },
  { code: 'AR', name: 'Arjantin', flag: '🇦🇷', dial: '54' },
  { code: 'CL', name: 'Şili', flag: '🇨🇱', dial: '56' },
  { code: 'CO', name: 'Kolombiya', flag: '🇨🇴', dial: '57' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', dial: '51' },
  { code: 'TM', name: 'Türkmenistan', flag: '🇹🇲', dial: '993' },
  { code: 'UZ', name: 'Özbekistan', flag: '🇺🇿', dial: '998' },
  { code: 'KG', name: 'Kırgızistan', flag: '🇰🇬', dial: '996' },
  { code: 'TJ', name: 'Tacikistan', flag: '🇹🇯', dial: '992' },
]

export const DEFAULT_COUNTRY = COUNTRIES.find((c) => c.code === 'TR')!
